#!/bin/bash
# Script to post an AI-generated comment to a GitHub issue with a standardized signature.
# Usage: ./ai_comment.sh <issue_number> <model_name> "comment text"

if [ "$#" -lt 3 ]; then
    echo "Usage: $0 <issue_number> <model_name> \"<comment_text>\""
    echo "Example: $0 42 'Gemini-1.5-Pro' 'This is my review...'"
    exit 1
fi

ISSUE_NUM=$1
MODEL_NAME=$2
COMMENT_TEXT=$3

# Build the final body
BODY="${COMMENT_TEXT}

---
🤖 *Generated by **${MODEL_NAME}***"

# Post the comment using gh
gh issue comment "$ISSUE_NUM" --body "$BODY"

if [ $? -eq 0 ]; then
    echo "Successfully posted comment to issue #$ISSUE_NUM as $MODEL_NAME"
else
    echo "Failed to post comment."
    exit 1
fi
